import json, os, threading, time, unittest, urllib.request
from app import init, Handler, ThreadingHTTPServer, worker
class ApiTest(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if os.path.exists('ecommerce.db'): os.remove('ecommerce.db')
        init(); cls.server=ThreadingHTTPServer(('127.0.0.1',8765),Handler); threading.Thread(target=cls.server.serve_forever,daemon=True).start(); threading.Thread(target=worker,daemon=True).start()
    @classmethod
    def tearDownClass(cls): cls.server.shutdown()
    def req(self,path,body=None,token=None,method=None):
        method=method or ('POST' if body is not None else 'GET')
        r=urllib.request.Request('http://127.0.0.1:8765/api/v1'+path,data=json.dumps(body).encode() if body is not None else None,headers={'Content-Type':'application/json',**({'Authorization':'Bearer '+token} if token else {})},method=method); return json.loads(urllib.request.urlopen(r).read())
    def test_login_demo_and_diagnosis(self):
        d=self.req('/auth/login',{'username':'admin','password':'admin123'}); t=d['access_token']; demo=self.req('/workspace/demo-data',{},t); pid=demo['product_id']; p=self.req('/products/'+str(pid),token=t); self.assertEqual(p['name'],'轻量防晒伞'); diag=self.req('/products/'+str(pid)+'/diagnoses/generate',{},t); self.assertIn('positioning',diag)
        plan=self.req('/products/'+str(pid)+'/creative-plans/main-images/generate',{},t); job=self.req('/products/'+str(pid)+'/creative-plans/'+str(plan['id'])+'/images/generate',{},t); self.assertEqual(job['job_status'],'pending'); time.sleep(2); detail=self.req('/products/'+str(pid),token=t); self.assertEqual(detail['jobs'][0]['job_status'],'succeeded'); self.assertEqual(len(detail['assets']),1); asset=detail['assets'][0]; updated=self.req('/products/'+str(pid)+'/assets/'+str(asset['id']),{'review_status':'approved','score':4.5},t,method='PATCH'); self.assertEqual(updated['review_status'],'approved')
        sku=self.req('/products/'+str(pid)+'/skus',{'sku_code':'S-1','sku_name':'标准','stock_qty':5,'warning_threshold':3},t); self.assertEqual(sku['stock_qty'],5); adj=self.req('/products/'+str(pid)+'/skus/'+str(sku['id'])+'/inventory-adjustments',{'change_qty':-2,'reason_text':'盘点'},t); self.assertEqual(adj['after_qty'],3); detail=self.req('/products/'+str(pid),token=t); self.assertTrue(any(x['low_stock'] for x in detail['skus'])); self.assertEqual(len(detail['inventory_movements']),1)
        dashboard=self.req('/workspace/dashboard',token=t); self.assertGreaterEqual(dashboard['low_stock_skus'],1); csv='product_id,sku_code,sku_name,price,stock_qty,warning_threshold\n'+str(pid)+',S-2,红色,89,8,5\n'+str(pid)+',S-3,,89,1,5\n'; preview=self.req('/workspace/imports/sku-inventory/preview',{'csv_text':csv},t); self.assertEqual(preview['valid_rows'],1); result=self.req('/workspace/imports/sku-inventory/commit',{'csv_text':csv},t); self.assertEqual(result['success_count'],1)
        store=self.req('/stores/'+str(demo['store_id']),token=t); self.assertEqual(store['product_count'],1); competitor=self.req('/products/'+str(pid)+'/competitors',{'name':'竞品','price':69},t); self.assertIn('id',competitor); link=self.req('/products/'+str(pid)+'/promotion-links',{'link_name':'测试链接','target_url':'https://example.com'},t); self.assertIn('tracking_code',link); ad=self.req('/products/'+str(pid)+'/ad-recommendations/generate',{},t); self.assertEqual(ad['confirm_status'],'pending')
        users=self.req('/users',token=t); self.assertEqual(len(users),3); account=self.req('/stores/'+str(demo['store_id'])+'/platform-accounts',{'platform':'taobao','account_name':'演示账号'},t); self.assertEqual(account['auth_status'],'not_connected'); confirmed=self.req('/products/'+str(pid)+'/ad-recommendations/'+str(ad['id'])+'/confirmation',{'confirm_status':'confirmed'},t,method='PATCH'); self.assertEqual(confirmed['confirm_status'],'confirmed'); exp=self.req('/products/'+str(pid)+'/ad-experiments',{'experiment_name':'主图 A/B'},t); self.assertEqual(exp['experiment_status'],'draft'); exp2=self.req('/products/'+str(pid)+'/ad-experiments/'+str(exp['id']),{'experiment_status':'confirmed'},t,method='PATCH'); self.assertEqual(exp2['experiment_status'],'confirmed')
if __name__=='__main__': unittest.main()
