"""create async operations tables"""
from alembic import op
import sqlalchemy as sa
revision='0003_operations'; down_revision='0002_core_catalog'; branch_labels=None; depends_on=None
def upgrade():
    op.create_table('generation_jobs',sa.Column('id',sa.Integer,primary_key=True),sa.Column('product_id',sa.Integer,sa.ForeignKey('products.id'),nullable=False),sa.Column('job_kind',sa.String(40),nullable=False),sa.Column('job_status',sa.String(30),nullable=False,server_default='pending'),sa.Column('attempts',sa.Integer,nullable=False,server_default='0'),sa.Column('error_message',sa.String(500))); op.create_index('ix_generation_jobs_product_id','generation_jobs',['product_id'])
    op.create_table('generation_job_events',sa.Column('id',sa.Integer,primary_key=True),sa.Column('job_id',sa.Integer,sa.ForeignKey('generation_jobs.id'),nullable=False),sa.Column('event_type',sa.String(40),nullable=False),sa.Column('event_message',sa.String(500)),sa.Column('created_at',sa.DateTime,server_default=sa.func.now()))
    op.create_table('generated_assets',sa.Column('id',sa.Integer,primary_key=True),sa.Column('product_id',sa.Integer,sa.ForeignKey('products.id'),nullable=False),sa.Column('job_id',sa.Integer,sa.ForeignKey('generation_jobs.id')),sa.Column('asset_type',sa.String(30),nullable=False),sa.Column('asset_url',sa.String(500),nullable=False),sa.Column('review_status',sa.String(30),nullable=False,server_default='pending'),sa.Column('score',sa.Float),sa.Column('remark',sa.String(500)))
    op.create_table('performance_records',sa.Column('id',sa.Integer,primary_key=True),sa.Column('product_id',sa.Integer,sa.ForeignKey('products.id'),nullable=False),sa.Column('period_start',sa.String(20),nullable=False),sa.Column('period_end',sa.String(20),nullable=False),sa.Column('impressions',sa.Integer,nullable=False,server_default='0'),sa.Column('clicks',sa.Integer,nullable=False,server_default='0'),sa.Column('conversions',sa.Integer,nullable=False,server_default='0'),sa.Column('spend',sa.Float,nullable=False,server_default='0'),sa.Column('revenue',sa.Float,nullable=False,server_default='0'),sa.Column('notes',sa.String(500)))
    op.create_table('review_reports',sa.Column('id',sa.Integer,primary_key=True),sa.Column('product_id',sa.Integer,sa.ForeignKey('products.id'),nullable=False),sa.Column('period_start',sa.String(20)),sa.Column('period_end',sa.String(20)),sa.Column('summary_text',sa.String(2000)),sa.Column('insights_json',sa.Text),sa.Column('next_actions_json',sa.Text),sa.Column('created_at',sa.DateTime,server_default=sa.func.now()))
def downgrade():
    op.drop_table('review_reports'); op.drop_table('performance_records'); op.drop_table('generated_assets'); op.drop_table('generation_job_events'); op.drop_index('ix_generation_jobs_product_id',table_name='generation_jobs'); op.drop_table('generation_jobs')
